### ISSUE TITLE
Bug Report: Uncentered Arrows in Keybinds Menu, and unable to hold shift to bypass pop-ups in fullscreen

### ISSUE THREAD

**Issue by PhxR3d** [YoshiCrafter29/YoshiCrafterEngine#263]
## Which target are you using?
- Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
2.0.0
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Any time there are issues with a script that cause a popup or anytime you open the keybinds menu.
## Please describe your issue. Provide extensive detail and images if possible.
The arrows in the keybinds menu aren't centered, and popups from script errors are unable to be bypassed while in fullscreen.
![image](https://user-images.githubusercontent.com/83072269/179650378-0f6db4fb-c002-40ce-bcd6-25994178e289.png)

**Comment by YoshiCrafter29** [comment]
script errors that are unable to be pressed while in fullscreen is actually a lime thing, made the error boxes force you off fullscreen.
second bug is fixed

**Comment by PhxR3d** [comment]
Update: After updating to 2.0.1, both issues still seem to be present.
